services:
  mongodb:
    image: 'mongo:latest'
    environment:
      - 'MONGO_INITDB_DATABASE=VDT'
    ports:
      - '27019:27017'
    networks:
      - vdt
  rabbitmq:
    image: 'pcloud/rabbitmq-stomp:latest'
    environment:
      - 'RABBITMQ_DEFAULT_PASS=admin'
      - 'RABBITMQ_DEFAULT_USER=admin'
    ports:
      - '5672:5672'
      - '15672:15672'
      - '61613:61613'
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 10s
    networks:
      - vdt
  vdtvideocall:
    image: vdt/videocall
    environment:
      - 'MONGO_INITDB_DATABASE=VDT'
    ports:
      - '8080:8080'
      - '8000:8000'
    depends_on:
      mongodb:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    networks:
      - vdt
  nginx:
    image: vdtnginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/ssl:/etc/nginx/ssl/
    depends_on:
      - vdtvideocall
    networks:
      - vdt
networks:
  vdt:
    driver: bridge